[tool.mypy]
python_version = "3.14"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = false
ignore_missing_imports = false

[tool.django-stubs]
django_settings_module = "marketplace.settings"

[tool.pyright]
include = ["api", "marketplace", "config"]
exclude = ["**/__pycache__", "**/migrations", "venv"]
reportMissingImports = true
reportMissingTypeStubs = false
pythonVersion = "3.14"
typeCheckingMode = "basic"
reportGeneralTypeIssues = false

[tool.flake8]
max-line-length = 158
extend-ignore = ["E203", "W503"]

[tool.black]
line-length = 158
target-version = ["py314"]

[tool.isort]
profile = "black"
line_length = 158

